In [1]:
# 1.	Import NumPy and print its version.
import numpy as np
print(np.__version__)

# numpy version is 2.4.3

2.2.6


In [2]:
# 2.	Make an array from the hours logged column.
import pandas as pd
df = pd.read_csv('it_services_tickets_cleaned.csv')
df.head()

hours_array = df['hours_logged'].values
print(hours_array[:5])

# hours_logged values are assigned to hours_array 

[  nan  1.34  7.   34.63 12.76]


/tmp/ipykernel_271802/2435767581.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('it_services_tickets_cleaned.csv')


In [3]:
# 3.	Print the shape, the size and the data type of that array.

print("shape: ",hours_array.shape)
print("size: ",hours_array.size)
print("type: ",hours_array.dtype)

# shape and size of array is 19380 and data type is float64

shape:  (19380,)
size:  19380
type:  float64


In [4]:
# 4.	Make an array of the numbers 1 to 50 using arange.
np_arange = np.arange(1,51)
print(np_arange)

# np.arrange(start, end+1) is used to make array form 1 tp 50

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [5]:
# 5.	Make 10 evenly spaced numbers between 0 and 100 using linspace.
linspace_array = np.linspace(0, 100, 10)
print(linspace_array)

# linespace(star, end, space) is used to make array

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [9]:
# 6.	Make an array of 10 zeros and an array of 10 ones.
zeros_array = np.zeros(10)
ones_array = np.ones(10)
print('Zeros array:', zeros_array)
print("Ones array:", ones_array)

#  np.zeros(length) is used to make array of 0s 
#  np.ones(length) is used to make arrya of 1s

Zeros array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones array: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [10]:
# 7.	Make a 3 by 3 array of random numbers using seed 42.
np.random.seed(42)
random_arr = np.random.rand(3,3)
print(random_arr)

# np.random.rand() generate the random values between 0 to 1 when seed is given it produces same result every time

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [11]:
# 8.	Make a 2-D array from the hours logged and billing rate columns.
hours_billing = df[['hours_logged','billing_rate_(usd)']].values
print(hours_billing)

# hours_billing 2-D array is made by providing list to the data frame 

[[  nan 39.45]
 [ 1.34 33.15]
 [ 7.   48.1 ]
 ...
 [  nan 38.76]
 [12.   58.59]
 [31.21   nan]]


In [12]:
# 9.	Print how many dimensions that 2-D array has.
hours_billing.ndim

# array.ndim display the dimension of the array

2

In [13]:
# 10.	Print the first 5 values of the hours array.
print(hours_billing[:5])

# array[:n] shows first n values of array

[[  nan 39.45]
 [ 1.34 33.15]
 [ 7.   48.1 ]
 [34.63 52.98]
 [12.76   nan]]


In [34]:
# 11.	Print the last 5 values of the hours array.
print(hours_billing[-5:])

# array[-n:] shows last n values of array

[[43.   29.81]
 [11.73 81.63]
 [  nan 38.76]
 [12.   58.59]
 [31.21   nan]]


In [35]:
# 12.	Print every second value from the first 20 values.
print(hours_billing[:20:2])

# array[:n:m] print first n values after m gap for each value

[[   nan  39.45]
 [  7.    48.1 ]
 [ 12.76    nan]
 [   nan    nan]
 [  1.66  72.37]
 [   nan  90.14]
 [ 11.63  79.54]
 [ 28.    64.78]
 [  0.59  71.84]
 [253.85    nan]]


In [36]:
# 13.	Reverse the array.
reversed_array = hours_billing[::-1]
print(reversed_array)

# array[::-1] is used to reverse the array

[[31.21   nan]
 [12.   58.59]
 [  nan 38.76]
 ...
 [ 7.   48.1 ]
 [ 1.34 33.15]
 [  nan 39.45]]


In [16]:
# 14.	Find the sum of the hours array.
print("sum of hours: ", np.nansum(hours_array))

# np.nansum(array) nansum is used beacuse there are some null values in the array which is 932344.04

sum of hours:  932344.04


In [17]:
# 15.	Find the mean, the minimum and the maximum of the hours array.
print("mean: ", np.nanmean(hours_array))
print("min: ", np.nanmin(hours_array))
print("max: ", np.nanmax(hours_array))

# np.nanmean(array), np.nanmin(array), np.nanmax(array) is used to calculate mean, minimum and maximum

mean:  64.06541881399025
min:  -12.5
max:  9888.01


In [18]:
# 16.	Find the standard deviation.
print("standard deviation: ", np.nanstd(hours_array))

# np.nanstd(array) is used to calculate standard deviation which is 498.42

standard deviation:  498.42863095465026


In [19]:
# 17.	Find the median.
print("median: ", np.nanmedian(hours_array))

# np.nanstd(array) is used to calculate standard deviation which is 13.05

median:  13.05


In [20]:
# 18.	Count how many values are missing in the array.
print("missing values: ", np.isnan(hours_array).sum())

# there are total 4827 missing values

missing values:  4827


In [21]:
# 19.	Find the mean while ignoring the missing values.
print("mean: ", np.nanmean(hours_array))

# mean is 64.06

mean:  64.06541881399025


In [24]:
# 20.	Replace all the missing values with 0.
hours_array = np.nan_to_num(hours_array,nan=0)
print("missing values: ", np.isnan(hours_array).sum())
# # np.nan_to_num(array, nan=0), after this missing values is 0

missing values:  0


In [28]:
# 21.	Count how many values are greater than 100.
print("values grater then 100: ", (hours_array > 100).sum())

# values grater then 100 is 616

values grater then 100:  616


In [29]:
# 22.	Show only the values that are greater than 100.
print(hours_array[hours_array > 100])

# array[array > n] is used to print the values that are grater then n

[ 253.85  128.   1900.66  133.35  373.68 5000.    723.5   101.04  152.
  311.49  139.26  216.05  369.   1385.33  181.82  182.62  947.07 5000.
  108.11  161.33  118.41 1225.    412.77  125.59  172.81  105.38  121.55
  442.   8760.    115.    191.45  102.69  121.89  169.42 8760.    261.95
  514.33  467.    295.53  434.99 8760.    103.   5000.    103.9  8760.
  150.58  552.44  181.11 5000.    196.39  161.42 1289.39  177.87  531.3
  104.    239.69  102.6   115.5  1095.18  377.07  104.27  103.11  194.
  144.    138.39  137.    837.55  132.    162.    349.    316.    138.4
  116.49  112.    162.91  146.31  155.61  142.63  122.4  5000.    165.
  281.    202.02  388.28 5000.    134.08  194.    519.    116.14  109.63
  116.76  107.02  108.53 2681.97  150.    128.2   183.   2962.15  154.
  603.    158.    149.    156.    193.45  180.   1564.13  528.52 8760.
  123.6  1408.19  194.2   179.8   102.87  153.47  613.99 5000.   5000.
  260.8   154.41  139.78  131.07  105.54 1859.26  199.74  140.4  1206

In [31]:
# 23.	Show the values that are between 10 and 50.
print(hours_array[(hours_array>=10) & (hours_array<=50)])

# array[(array >= n) & (array <= m)] used to print values between n and m

[34.63 12.76 15.3  ... 11.73 12.   31.21]


In [32]:
# 24.	Count how many values are negative.
print("negative values: ", (hours_array < 0).sum())

# there are 50 negative values

negative values:  50


In [33]:
# 25.	Replace all the negative values with 0.
hours_array[hours_array < 0] = 0
print("negative values: ", (hours_array < 0).sum())

# array[array < 0] = 0 is used to replace the negative with 0

negative values:  0


In [34]:
# 26.	Sort the array from smallest to largest.
sorted_hours_array = np.sort(hours_array)
print(sorted_hours_array)

# np.sort(array) is used to sort array

[   0.      0.      0.   ... 8760.   9888.01 9888.01]


In [35]:
# 27.	Find the position of the largest value.
print("postiton of largest value: " ,np.argmax(hours_array))

# larget position is 10033

postiton of largest value:  10033


In [36]:
# 28.	Find the position of the smallest value.
print("postiton of smallest value: " ,np.argmin(hours_array))

# smallest postion is 0

postiton of smallest value:  0


In [37]:
# 29.	Find the 5 largest values.
print(np.sort(hours_array)[-5:])
# arry is sorted and last five values is showed

[8760.   8760.   8760.   9888.01 9888.01]


In [38]:
# 30.	Round every value to 1 decimal place.
rounded_hours_array = np.round(hours_array, 1)
print(rounded_hours_array[:10])

# np.round(array, n) this rouunds array to n points

[ 0.   1.3  7.  34.6 12.8 15.3  0.   9.   1.7  0. ]


In [39]:
# 31.	Multiply every value by 2.
multiply_every_array = hours_array * 2
print(multiply_every_array[:10])

# (array * n) multiplies every value by n

[ 0.    2.68 14.   69.26 25.52 30.6   0.   18.    3.32  0.  ]


In [40]:
# 32.	Add 10 to every value.
add_every_array = hours_array + 10
print(add_every_array[:10])

# (array + n) adds every value by n

[10.   11.34 17.   44.63 22.76 25.3  10.   19.   11.66 10.  ]


In [41]:
# 33.	Multiply the hours array by the billing rate array.
billing_rate_array = np.nan_to_num(df['billing_rate_(usd)'].values, nan=0)

new_arr = hours_array * billing_rate_array
print(new_arr[:10])

# first billing_rate arrays null values in converted to 0 then mutliplied by hours_array

[   0.       44.421   336.7    1834.6974    0.        0.        0.
  432.54    120.1342    0.    ]


In [77]:
# 34.	Check whether the two arrays have the same length.
print("hours_array len: ",len(hours_array))
print("billing_rate_array len: ",len(billing_rate_array))
len(hours_array) == len(billing_rate_array)

# yes both array have same length

hours_array len:  19380
billing_rate_array len:  19380


True

In [78]:
# 35.	Use np.where to mark values above 24 as slow and the rest as fast.
newarr = np.where(hours_array > 24, 'slow', 'fast')
print(newarr)

['fast' 'fast' 'fast' ... 'fast' 'fast' 'slow']


In [48]:
# 36.	Make an array of the unique priority values.

priority_array = df['priority'].fillna('missing').values
unique_priorities = np.unique(priority_array)
print(unique_priorities)

# first replace missing values with missing and then remove duplicates using np.unique(array) 

['--' '1' '2' '3' '4' '?' 'CRITICAL' 'Critical' 'HIGH' 'High' 'LOW' 'Low'
 'MEDIUM' 'Medium' 'P1' 'P1 - Critical' 'P2' 'P3' 'P4' 'PRIORITY' 'high'
 'low' 'medium' 'missing' 'na' 'p1' 'p2' 'p3' 'p4']


In [49]:
# 37.	Count how many times each unique priority value appears.
unique_priorities, counts = np.unique(priority_array, return_counts=True)
for p, c in zip(unique_priorities, counts):
    print(p, c)

# find unique in priority_array and its count and then display the priority and count 

-- 31
1 778
2 815
3 807
4 742
? 33
CRITICAL 790
Critical 814
HIGH 812
High 782
LOW 797
Low 764
MEDIUM 789
Medium 773
P1 760
P1 - Critical 789
P2 762
P3 810
P4 770
PRIORITY 1
high 779
low 794
medium 774
missing 448
na 54
p1 808
p2 789
p3 786
p4 729


In [50]:
# 38.	Take the first 100 values and reshape them into a 10 by 10 array.

reshaped_array = hours_array[:100].reshape(10, 10)
print(reshaped_array)

# using reshape(rows, cols) we can reshape the array

[[0.00000e+00 1.34000e+00 7.00000e+00 3.46300e+01 1.27600e+01 1.53000e+01
  0.00000e+00 9.00000e+00 1.66000e+00 0.00000e+00]
 [0.00000e+00 1.44000e+00 1.16300e+01 7.23100e+01 2.80000e+01 1.01600e+01
  5.90000e-01 7.00000e+00 2.53850e+02 4.20000e+00]
 [5.08100e+01 8.01000e+00 6.79400e+01 0.00000e+00 3.27100e+01 0.00000e+00
  6.91000e+00 3.08400e+01 3.51000e+00 4.34000e+00]
 [1.80000e+01 3.14400e+01 3.42000e+00 2.44600e+01 0.00000e+00 1.30000e+01
  3.00200e+01 1.15100e+01 6.30200e+01 1.03000e+00]
 [0.00000e+00 3.92000e+00 2.02200e+01 2.41500e+01 8.40000e+01 0.00000e+00
  2.70000e+01 0.00000e+00 4.00000e+00 2.76000e+00]
 [1.12600e+01 2.40000e+01 5.26000e+00 1.40000e+01 5.00000e+00 1.14100e+01
  0.00000e+00 1.80000e+01 1.28000e+02 1.54000e+01]
 [1.90066e+03 4.00000e+00 3.00000e+00 9.00000e+00 1.33350e+02 0.00000e+00
  4.00000e+00 0.00000e+00 2.00000e+00 0.00000e+00]
 [2.05100e+01 1.13300e+01 5.99100e+01 1.00000e+00 2.29700e+01 0.00000e+00
  0.00000e+00 0.00000e+00 3.40000e+01 1.49200e+01]


In [52]:
# 39.	Transpose that 10 by 10 array.
transposed_array = reshaped_array.T
print(transposed_array)

# using array.T we can transpose the array

[[0.00000e+00 0.00000e+00 5.08100e+01 1.80000e+01 0.00000e+00 1.12600e+01
  1.90066e+03 2.05100e+01 1.91700e+01 1.30000e+01]
 [1.34000e+00 1.44000e+00 8.01000e+00 3.14400e+01 3.92000e+00 2.40000e+01
  4.00000e+00 1.13300e+01 1.78600e+01 1.09100e+01]
 [7.00000e+00 1.16300e+01 6.79400e+01 3.42000e+00 2.02200e+01 5.26000e+00
  3.00000e+00 5.99100e+01 9.21000e+00 8.00000e+00]
 [3.46300e+01 7.23100e+01 0.00000e+00 2.44600e+01 2.41500e+01 1.40000e+01
  9.00000e+00 1.00000e+00 5.40000e+01 3.81000e+00]
 [1.27600e+01 2.80000e+01 3.27100e+01 0.00000e+00 8.40000e+01 5.00000e+00
  1.33350e+02 2.29700e+01 0.00000e+00 3.73680e+02]
 [1.53000e+01 1.01600e+01 0.00000e+00 1.30000e+01 0.00000e+00 1.14100e+01
  0.00000e+00 0.00000e+00 2.00000e+01 1.13800e+01]
 [0.00000e+00 5.90000e-01 6.91000e+00 3.00200e+01 2.70000e+01 0.00000e+00
  4.00000e+00 0.00000e+00 6.00000e+00 3.36700e+01]
 [9.00000e+00 7.00000e+00 3.08400e+01 1.15100e+01 0.00000e+00 1.80000e+01
  0.00000e+00 0.00000e+00 1.15600e+01 5.80000e-01]


In [54]:
# 40.	Flatten it back into a 1-D array.
flattened_array = transposed_array.flatten()
flattened_array[:10]

# using array.flatten() we can convert it into 1-D array

array([   0.  ,    0.  ,   50.81,   18.  ,    0.  ,   11.26, 1900.66,
         20.51,   19.17,   13.  ])

In [55]:
# 41.	Join two arrays together using np.concatenate.
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
concated_arr = np.concatenate((arr1, arr2))
print(concated_arr)

# np.concatenate((arr1, arr2)) is used to join two array together

[1 2 3 4 5 6 7 8]


In [56]:
# 42.	Split an array into 5 equal parts.
split_arr = np.split(np_arange,5)
print(split_arr)

# np.split(array, n) it splits array into n equal parts

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]), array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40]), array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50])]


In [57]:
# 43.	Find the 25th, 50th and 75th percentile.
percentile = np.nanpercentile(hours_array,[25,50,75])
print("25th :", percentile[0])
print("50th :", percentile[1])
print("75th :", percentile[2])

# np.nanpercentile(array,[list]) is used to calculate percentile

25th : 0.0
50th : 6.48
75th : 23.67


In [58]:
# 44.	Find the cumulative sum of the first 20 values.
cum_sum = np.nancumsum(hours_array[:20])
print(cum_sum)

# np.nancumsum(array) is used to ge cumulative sum

[  0.     1.34   8.34  42.97  55.73  71.03  71.03  80.03  81.69  81.69
  81.69  83.13  94.76 167.07 195.07 205.23 205.82 212.82 466.67 470.87]


In [59]:
# 45.	Find the difference between each value and the one before it using np.diff.
diff = np.diff(hours_array[:10])
print(diff)

# np.diff(array) is used find difference 

[  1.34   5.66  27.63 -21.87   2.54 -15.3    9.    -7.34  -1.66]


In [60]:
# 46.	Keep every value inside the range 0 to 100 using np.clip.
clipped = np.clip(hours_array,0,100)
print(clipped)

# np.clip(array,n,m) is used to keep array values inside the n and m

[ 0.    1.34  7.   ...  0.   12.   31.21]


In [61]:
# 47.	Convert the array to whole numbers.
whole_no = hours_array.astype(int)
print(whole_no)

# array.astype(int) i used to convert array to whole number

[ 0  1  7 ...  0 12 31]


In [62]:
# 48.	Copy the array, change one value in the copy, and show that the original did not change.
arr1 = np.array([1,2,3,4])
arr2 = arr1.copy()
arr2[0] = 9
print("arr1: ",arr1)
print( "arr2: ",  arr2)

# array.copy() is used to copy the array

arr1:  [1 2 3 4]
arr2:  [9 2 3 4]


In [63]:
# 49.	Save the array to a .npy file and load it back.
np.save("hours_array.npy", hours_array)
loaded_hours_arr = np.load("hours_array.npy")
print(loaded_hours_arr)

#  file is saved as hours_array.npy


[ 0.    1.34  7.   ...  0.   12.   31.21]


In [64]:
# 50.	Find the total revenue using np.dot on the hours array and the rate array.
total_revenue = np.dot(hours_array, billing_rate_array)
print("Total revenue: ", total_revenue)

# np.dot(arr1, arr2) is used to find dot product

Total revenue:  49516339.0764
